<a href="https://colab.research.google.com/github/arayen84/Numpy_tutorial/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# to build 1D numpy array with value
x=np.arange(1,11)
print(x)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# do element-wise operation

x1=np.array([2,4,6,8])
x2=np.array([1,2,3,4])
x3 = np.add(x1,x2)
x4 = np.multiply(x1,x2)
print(x3)
print(x4)

[ 3  6  9 12]
[ 2  8 18 32]


In [ ]:
# reshaping array

x6 = x.reshape(2,5)
print(x6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Finding statistic

d1 = np.array([1,2,3,4,5,6,7,8,9,10])
mean = np.mean(d1)
print("mean :",mean)
st=np.std(d1)
print("Standard deviation :",st)

mean : 5.5
Standard deviation : 2.8722813232690143


In [ ]:
# concatenation

d2 = np.array([9,8,6])
d3 = np.array([3,22,11])
vd2 = np.vstack([d2,d3])
print("vertical stack : ",vd2)

print("----------------")
hd3 = np.hstack([d3,d3])
print("Horizantal stack :",hd3)

vertical stack :  [[ 9  8  6]
 [ 3 22 11]]
----------------
Horizantal stack : [ 3 22 11  3 22 11]


In [ ]:
# slicing & indexing

d4 = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99,2,1,10])
d5 = d4[3:7]
print(d5)

[44 55 66 77]


In [ ]:
# universal function
# add 5 to each score using a NumPy ufunc

d6 = np.array([50,60,75,80,91])
d7 = np.add(d6,5)
print("After added 5 :",d7)

After added 5 : [55 65 80 85 96]


In [ ]:
# masked array
# masked array from a NumPy array where values less than 3 are masked.

import numpy.ma as ma
d8 = ma.masked_less(d4,33)
print(d8)

[-- -- 33 44 55 66 77 88 99 -- -- --]


In [ ]:
# Finding maximum & minimum

m1 = np.max(d4)
print("maximum : ",m1)
print("---------")
m2 = np.min(d4)
print("minimum :",m2)
print("---------")
m3 = np.argmax(d4)
print("argmax :",m3)
print("----------")
m4 = np.argmin(d4)
print("argmin :",m4)


maximum :  99
---------
minimum : 1
---------
argmax : 8
----------
argmin : 10


In [ ]:
# Conditional Selection
# select all values greater than 7.

value = d4[d4>50]
print("Values grater than 50 :",value)

Values grater than 50 : [55 66 77 88 99]


In [ ]:
# creating empty & full numpy array

v = np.empty([4,2])
print(" create empty :" ,v)
print("--------")
v1 = np.full([4,3],92)
print("create full : ",v1)

 create empty : [[4.87013449e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
--------
create full :  [[92 92 92]
 [92 92 92]
 [92 92 92]
 [92 92 92]]


In [ ]:
# Filled with all zeros
v2 = np.zeros((3,4), dtype=int)
print(v2)
v2a = np.zeros((5,6),dtype=float)
print(v2a)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
# Filled with ones
v3 = np.ones([4,4] , dtype=int)
print(v3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# find contains specified row
v4 = np.array([[1,2,3,4,5],[6,7,8,9],[11,12,13,14,15],[16,17,18,19,20]])
print([1,2,3,4,5] in v4.tolist())
print([16,17,18,19,20] in v4.tolist())
print([23,43,99,1] in v4.tolist())

True
True
False


<ipython-input-85-6736d3827344>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  v4 = np.array([[1,2,3,4,5],[6,7,8,9],[11,12,13,14,15],[16,17,18,19,20]])


In [ ]:
# remove non numeric value
#v5 = np.array([[1,2,3,4,5],[6,"np.nan","np.nan"]])
#v55 = np.array([np.nan if not str(e).replace(".","",1).isdigit() else float(e) for e in v5.flat], dtype=float).reshape(v5.shape)
#cleaned_data = v55[~np.isnan(v55).any(axis=1)]









In [ ]:
# squeeze in python
# to remove the single-dimention of array
before_squeeze = np.array([[[1,2,3,4],[5,6,7,8],[9,8,4,3]]])
print("shape before squeeze : ",before_squeeze.shape)
print("-----------------")
after_squeeze = np.squeeze(before_squeeze)
print("After squeeze : ",after_squeeze)
print("shape after squeeze : ",after_squeeze.shape)


shape before squeeze :  (1, 3, 4)
-----------------
After squeeze :  [[1 2 3 4]
 [5 6 7 8]
 [9 8 4 3]]
shape after squeeze :  (3, 4)


In [ ]:
# find the no of occurences
given_array = np.array([[2, 8, 9, 4],[9, 4, 9, 4],[4, 5, 9, 7], [2, 9, 4, 3]])
subarray_to_find =[9,4]
find_occ = sum(1 for row in given_array if np.array_equal(row, subarray_to_find))
print("find occurence :" ,find_occ)

find occurence : 0
