<a href="https://colab.research.google.com/github/arayen84/Numpy_tutorial/blob/main/Numpy_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x= np.array(["hello ", 1 , "World"])
print(x[0]+x[2])

hello World


In [ ]:
y = np.array( [ [1,2] , [3,4] ,[5,6]])
print(y)
print(y.ndim)
print(y[0])
print(y[0],y[2])
print(y[0,1],y[2][1])

[[1 2]
 [3 4]
 [5 6]]
2
[1 2]
[1 2] [5 6]
2 6


In [ ]:
z=np.array( [ [ [1,2,3], [4,5,6]]])
print(z)
print("----")
print(z[0])
print("----")
print(z[0,1])
print("----")
print(z[0,1,2])

[[[1 2 3]
  [4 5 6]]]
----
[[1 2 3]
 [4 5 6]]
----
[4 5 6]
----
6


In [ ]:
 Z1=np.array([ 1,2,3,4,5,6,7,88,78,56,456,9])
 print(Z1)
 print("------")
 print(Z1[1:7])
 print("------")
 print(Z1[1:7:2])


[  1   2   3   4   5   6   7  88  78  56 456   9]
------
[2 3 4 5 6 7]
------
[2 4 6]


In [ ]:
Z2 = np.array( [[1,2,3], [4,5,6], [7,8,9]])
print(Z2)
print("-------")
print(Z2[1])
print("-------")
print(Z2[1,1:2])
print("------")
print(Z2[2,1:])
print("------")
print(Z2[0:2,2])
print("------")
print(Z2[0:2,1:1])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------
[4 5 6]
-------
[5]
------
[8 9]
------
[3 6]
------
[]


In [ ]:
#convert number to string

x4=np.array([1,2,3,4,5])
print(x4)
x3=np.array([1,2,3,4,5],dtype = "S")
print(x3)


In [ ]:
# using same array in different variable name
x5=np.array([1,2,3,4,5])
new_x5=x5.astype("S")
print(new_x5.dtype)

In [ ]:
# numpy cpoy & view
x6=np.array([1,2,3,4,5,6])
y=x6.copy()
y1=x6.view()
x6[1]=2000
x6[3]=3000
print("x6 : ",x6)
print("y : ",y)
print("y1 : ",y1)

In [ ]:
# Array shape & reshape
x7=np.array([ [1,2,3,4], [5,6,7,8] ])
print(x7.shape)

(2, 4)


In [ ]:
x71=np.array([1,2,3,4],ndmin=3)
print(x71)
print(x71.shape)

[[[1 2 3 4]]]
(1, 1, 4)


In [ ]:
x8=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(x8.reshape(4,2,2))

In [ ]:
# numpy iterating

s1=np.array([1,2,3,4,5,6])
for i in s1:
  print(i)

1
2
3
4
5
6


In [ ]:
s2=np.array([[1,2,3],[4,5,6]])
for i in s2:
  for j in i:
    print(j)

1
2
3
4
5
6


In [ ]:
s3=np.array([[[1,2,3],[7,8,9]]])
for i in s3:
  for j in i:
    for n in j:

       print(n)


In [ ]:
s4=np.array([[[1,2,3],[4,5,6],[7,8,9],[11,12,13]]])
for i in np.nditer(s4):
  print(i)

In [ ]:
s5=np.array([1,2,3,4])
for i in np.nditer(s5,flags=["buffered"],op_dtypes="S"):
  print(i)

In [ ]:
s6=np.array([[12,2,3,9,11],[5,6,7,8,12]])
for i in np.nditer(s6 [:, : : 2]):  # [:,:] -> take all rows & column :2 -> slicing by 2
  print(i)



12
3
11
5
7
12


In [45]:
s7=np.array([[19,29,39],[4,5,6]])
for i in np.ndenumerate(s7):

     print(i)

((0, 0), 19)
((0, 1), 29)
((0, 2), 39)
((1, 0), 4)
((1, 1), 5)
((1, 2), 6)


In [55]:
a1=np.array([[9,8,6],[88,99,9]])
a2=np.array([[3,4,5],[33,44,9]])
a3=np.concatenate((a1,a2),axis=1)
a4=np.hstack((a1,a2))
a5=np.vstack((a1,a2))
a6=np.dstack((a1,a2))
print(a3)
print("printing row :",a4)
print("printing row :",a5)
print("print depth :", a6)

[[ 9  8  6  3  4  5]
 [88 99  9 33 44  9]]
printing row : [[ 9  8  6  3  4  5]
 [88 99  9 33 44  9]]
printing row : [[ 9  8  6]
 [88 99  9]
 [ 3  4  5]
 [33 44  9]]
print depth : [[[ 9  3]
  [ 8  4]
  [ 6  5]]

 [[88 33]
  [99 44]
  [ 9  9]]]
