<a href="https://colab.research.google.com/github/arayen84/Numpy_tutorial/blob/main/Numpy_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
from numpy import random
import numpy as np

## **randint
**

In [ ]:
x=random.randint(200)
print(x)

78


In [ ]:
# to print more than 1 random number use SIZE variable
xx=random.randint(100,size=8)
print(xx)

[66 89 11 39 36 36 21 12]


In [ ]:
# to print 2-dimentional use SIZE=(a,b)
xx1=random.randint(50,size=(4,5))
print(xx1)

[[15 30  3 30 33]
 [27 46  3  4 36]
 [18 46  3 28  4]
 [ 3 39  2 49 20]]


In [ ]:
# tp print 3-dimentional use SIZE=(a,b,c)
xx2=random.randint(150,size=(4,5,3))
print(xx2)

[[[113  65  72]
  [139   9  55]
  [ 96  96  80]
  [ 91 112 115]
  [ 53  45  56]]

 [[  4  11 130]
  [ 65  16  21]
  [ 37  18   9]
  [132  90 116]
  [ 60  25  93]]

 [[ 95 111 144]
  [125 113 114]
  [ 13  71  34]
  [ 47   1  53]
  [ 33   1  26]]

 [[ 99  14  79]
  [149  60  52]
  [116  49 110]
  [103  99  11]
  [138 133 148]]]


## **rand**


In [ ]:
# print 0 to 1 use rand
x1=random.rand()
print(x1)

0.32482792638989333


# **choice()**


In [19]:
x2=random.choice([2,3,9,7,5,8],size=(4,3))
print(x2)

[[8 9 2]
 [3 5 7]
 [2 5 5]
 [7 7 5]]


# data distribution
p=0 to 0.9 (probability)

In [30]:
x3=random.choice([2,3,4,5],p=[0.6,0.2,0.1,0.1],size=(25))
print(x3)

[2 2 2 5 3 2 2 3 4 2 2 2 2 5 2 2 2 2 2 4 2 2 3 5 2]


# permutation

In [34]:
#shuffle
x=np.array([2,3,4,9,8])
random.shuffle(x)
print(x)

[9 4 2 8 3]


In [42]:
#using permutaion
x4=np.array([4,5,9,2,1,6])
y=random.permutation(x4)
print("changed array :",y)
print("Unchanged array :",x4)

changed array : [2 5 6 4 1 9]
Unchanged array : [4 5 9 2 1 6]
