<a href="https://colab.research.google.com/github/arayen84/Numpy_tutorial/blob/main/practice_numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Numpy Statistics**

In [ ]:
import numpy as np

In [ ]:
# Write a Python program to find the maximum and minimum value of a given flattened array.
find_min_max = np.arange(4).reshape((2,2))
print("2D : ",find_min_max)
find_max = np.amax(find_min_max)
print("maximum : ",find_max)
find_min = np.amin(find_min_max)
print("minimum : ",find_min)

2D :  [[0 1]
 [2 3]]
maximum :  3
minimum :  0


In [ ]:
# Write a NumPy program to get the minimum and maximum value of a given array along the second axis.
find_min_max_1 = np.arange(6).reshape((2,3))
print("2D array : ",find_min_max_1)
find_max1 = np.amax(find_min_max_1,axis=1)
print("max : ",find_max1)
find_min1 = np.amin(find_min_max_1,axis=1)
print("min : ",find_min1)

2D array :  [[0 1 2]
 [3 4 5]]
max :  [2 5]
min :  [0 3]


In [ ]:
# Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.
find_diff = np.arange(12).reshape((2,6))
print("original array : ",find_diff)
find_diff_max = np.amax(find_diff,axis=1)
print("max : ",find_diff_max)
find_diff_min = np.amin(find_diff,axis=1)
print("min : ",find_diff_min)
arr_diff = find_diff_max - find_diff_min
print("Difference bet max,min : ",arr_diff)
find_peak = np.ptp(find_diff,axis =1)
print("ptp : ",find_peak)

original array :  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
max :  [ 5 11]
min :  [0 6]
Difference bet max,min :  [5 5]
ptp :  [5 5]


In [ ]:
# Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.
find_percent = np.arange(12).reshape((2,6))
print("original : ",find_percent)
find_percentile = np.percentile(find_percent,80,axis =1)
print("80% of element : ",find_percentile)

original :  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
80% of element :  [ 4. 10.]


In [ ]:
# Write a NumPy program to compute the median of flattened given array.
# Note: First array elements raised to powers from second array
find_median = np.arange(12).reshape((2,6))
print("original : ",find_median)
find_arr_median = np.median(find_median)
print("median : ",find_arr_median)

original :  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
median :  5.5


In [ ]:
# Write a NumPy program to compute the weighted of a given array.
ori_arr = np.arange(12)
print("original : ",ori_arr)
wei = np.arange(12)
print("weight : ",wei)
cal_weight = np.average(ori_arr,weights=wei)
print("sum : ",cal_weight)

original :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
weight :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
sum :  7.666666666666667


In [ ]:
# Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis.
find_m_s_v = np.arange(6)
print("original : ",find_m_s_v)
find_mean = np.mean(find_m_s_v)
print("mean : ",find_mean)
find_stand = np.std(find_m_s_v)
print("standard deviation : ",find_stand)
find_variance = np.var(find_m_s_v)
print("vaniance : ",find_variance)

original :  [0 1 2 3 4 5]
mean :  2.5
standard deviation :  1.707825127659933
vaniance :  2.9166666666666665


In [ ]:
# Write a NumPy program to compute cross-correlation of two given arrays.
cor_arr = np.arange(3)
print("arr1 : ",cor_arr)
cor_arr2 = np.array([4,5,6])
print("arr2 : ",cor_arr2)
find_cross = np.correlate(cor_arr,cor_arr2)
print(find_cross)


arr1 :  [0 1 2]
arr2 :  [4 5 6]
[17]


In [ ]:
#Write a NumPy program to compute pearson product-moment correlation coefficients of two given arrays.
