<a href="https://colab.research.google.com/github/arayen84/Numpy_tutorial/blob/main/practice_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Random**

In [ ]:
import numpy as np
from numpy import random

In [ ]:
#Write a NumPy program to generate five random numbers from the normal distribution.

gen_random = np.random.normal(size=5)
print(gen_random)

[ 1.54795041  0.85620713 -1.14454072 -0.72326967  0.21208467]


In [ ]:
# Write a NumPy program to generate six random integers between 10 and 30.
gen_integer = np.random.randint(10,30,size=6)
print(gen_integer)

[14 25 22 12 16 17]


In [ ]:
# Write a NumPy program to create a 3x3x3 array with random values.
ran_matrix = np.random.random((3,3,3))
print(ran_matrix)

[[[0.90096401 0.32188818 0.05079261]
  [0.62109843 0.18421542 0.24954138]
  [0.81774163 0.71110195 0.15850014]]

 [[0.26127673 0.01435403 0.18917779]
  [0.47459603 0.78081874 0.33944391]
  [0.13223711 0.8331931  0.38771863]]

 [[0.00370068 0.64720536 0.57665839]
  [0.95783876 0.42366142 0.38794702]
  [0.60200384 0.03435543 0.85059183]]]


In [ ]:
# Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.
find_5 = np.random.random((5,5))
print(find_5)
print("maximum :",np.max(find_5))
print("minimum :",np.min(find_5))

[[0.31893568 0.33236267 0.24268656 0.63897769 0.3345668 ]
 [0.4076128  0.922496   0.37797249 0.10917458 0.52784491]
 [0.63695103 0.98315393 0.48833996 0.1433278  0.13599615]
 [0.70513168 0.8116572  0.96116872 0.36897598 0.46876961]
 [0.26555315 0.00368042 0.72531143 0.42013155 0.85620609]]
maximum : 0.9831539332582753
minimum : 0.0036804172150376457


In [ ]:
# Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.
extract_val = np.random.random((10,4))
print(extract_val)
find_f5 = extract_val[:5,:]
print("first 5 row : ",find_5)

[[0.61427101 0.21840578 0.24132418 0.10609524]
 [0.2298984  0.81566034 0.06463015 0.50636219]
 [0.72247932 0.98366997 0.75639198 0.74069992]
 [0.15839685 0.60970977 0.01637745 0.41484921]
 [0.2765542  0.15484927 0.23733642 0.67237732]
 [0.96288455 0.66142712 0.71767507 0.7497962 ]
 [0.35107099 0.62370883 0.0072425  0.79146058]
 [0.7295995  0.07500068 0.25615441 0.08079941]
 [0.45741909 0.70933291 0.19470218 0.49216824]
 [0.52061633 0.20715739 0.05352911 0.37175067]]
first 5 row :  [[0.31893568 0.33236267 0.24268656 0.63897769 0.3345668 ]
 [0.4076128  0.922496   0.37797249 0.10917458 0.52784491]
 [0.63695103 0.98315393 0.48833996 0.1433278  0.13599615]
 [0.70513168 0.8116572  0.96116872 0.36897598 0.46876961]
 [0.26555315 0.00368042 0.72531143 0.42013155 0.85620609]]


In [ ]:
#  Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).
shuff_num = np.arange(10)
print("before shuffle : ",shuff_num)
np.random.shuffle(shuff_num)
print("after shuffle : ",np.random.permutation(shuff_num))


before shuffle :  [0 1 2 3 4 5 6 7 8 9]
after shuffle :  [0 2 6 1 4 7 9 5 8 3]


In [ ]:
# Write a NumPy program to normalize a 3x3 random matrix.
nor_mat = np.random.random([3,3])
print(nor_mat)
max_val =np.max(nor_mat)
min_val =np.min(nor_mat)
print("max :",max_val)
print("min :",min_val)
print("after normal :",(nor_mat- min_val)/(max_val - min_val))

[[0.53209261 0.01351076 0.89219193]
 [0.71618662 0.37715481 0.41118716]
 [0.54163397 0.84307041 0.56835811]]
max : 0.8921919319471824
min : 0.013510755218198667
after normal : [[0.59018205 0.         1.        ]
 [0.79969377 0.41385211 0.45258327]
 [0.60104078 0.94409631 0.6314547 ]]


In [ ]:
# Write a NumPy program to create a random vector of size 10 and sort it.
ran_vec = np.random.random(size=10)
print("random_vector : ",ran_vec)
do_sort = np.sort(ran_vec)
print("After sorting : ",do_sort)

random_vector :  [0.12517496 0.26016292 0.33436254 0.71451775 0.13999582 0.35069506
 0.0717224  0.35266379 0.53017579 0.80986417]
After sorting :  [0.0717224  0.12517496 0.13999582 0.26016292 0.33436254 0.35069506
 0.35266379 0.53017579 0.71451775 0.80986417]


In [ ]:
# Write a NumPy program to find the nearest value from a given value in an array.
find_near = np.random.uniform(1,22,5)
print(find_near)
val = 4
find_near_val = find_near.flat[np.abs(find_near - val).argmin()]
print("nearest value : " ,find_near_val)


[10.85258454 13.45782438 16.30555101 12.609702   12.00645481]
nearest value :  10.852584537150646


In [ ]:
# Write a NumPy program to check two random arrays are equal or not.
arr1 = np.random.randint(1,5,4)
arr2 = np.random.randint(1,5,4)
print(arr1)
print(arr2)
print(np.allclose(arr1,arr2))

[3 1 3 4]
[3 1 2 2]
False


In [ ]:
# Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.
replace_with_max = np.random.random(15)
print("random vector :",replace_with_max)
replace_with_max[replace_with_max.argmax()] = -1
print("after replace with -1 :",replace_with_max)


random vector : [0.46107368 0.77305142 0.89466258 0.77873275 0.56580255 0.15528971
 0.53000827 0.75400826 0.77223977 0.83676278 0.7122719  0.7796667
 0.51007472 0.38997438 0.46120314]
after replace with -1 : [ 0.46107368  0.77305142 -1.          0.77873275  0.56580255  0.15528971
  0.53000827  0.75400826  0.77223977  0.83676278  0.7122719   0.7796667
  0.51007472  0.38997438  0.46120314]


In [ ]:
# Write a NumPy program to find the most frequent value in an array.
find_frequent = np.random.randint(0,10,40)
print("Frequent array :",find_frequent)
find_fre_val = np.bincount(find_frequent).argmax()
print("most frequent value :",find_fre_val)

Frequent array : [8 6 9 0 5 5 7 8 5 5 0 3 1 3 3 5 5 4 4 4 0 0 4 6 2 7 8 6 9 7 3 6 5 4 7 3 4
 7 1 5]
most frequent value : 5


In [ ]:
# Write a NumPy program to convert cartesian coordinates to polar coordinates of a random 10x2 matrix representing cartesian coordinates.
find_carte = np.random.random((10,2))
print("cartesian : ",find_carte)
x,y = find_carte[:,0],find_carte[:,1]
sq = np.sqrt(x**2 + y**2)
pol = np.arctan2(y,x)
print("Polar : ",pol)


cartesian :  [[0.91602539 0.2574379 ]
 [0.58584233 0.09788472]
 [0.44719458 0.73910248]
 [0.69654897 0.54554512]
 [0.0389996  0.52390283]
 [0.69447603 0.90757974]
 [0.26103643 0.61133236]
 [0.44538684 0.89466699]
 [0.86845104 0.95884963]
 [0.68791087 0.68238475]]
Polar :  [0.27397094 0.16555443 1.02667124 0.66441986 1.49649285 0.91764075
 1.16723632 1.10889091 0.83482897 0.78136539]


In [ ]:
# Write a NumPy program to find the closest value (to a given scalar) in an array.
array_val=np.random.randint(0,100,40)
print("original val :",array_val)
val_to_compare = np.random.randint(1,100)
print("value to compare :",val_to_compare)
nearest = (np.abs(array_val - val_to_compare)).argmin()
print(nearest)
print("nearest value is. : ",array_val[nearest])

original val : [65 53 74 89 65  6 27 13 82 82 62 53 30 35 41 22 70 95 82 20 69 73 52 28
 54 84 19 71 61  4 23 91 77 56  8  0 65 59 66 49]
value to compare : 72
21
nearest value is. :  73


In [ ]:
# Write a NumPy program to get the n largest values of an array.
find_large = np.random.randint(0,20,9)
print("find largest value :",find_large)
large_val = np.argmax(find_large)
print("large value :",find_large[large_val])

find largest value : [ 4  5  6  7 15  5 19  1 18]
large value : 19


In [ ]:
# Write a NumPy program to create a three-dimension array with shape (300,400,5) and set to a variable. Fill the array elements with values using unsigned integer (0 to 255).
np.random.seed(32)
num = np.random.randint(low =0,high=256,size=(300,400,5),dtype=np.uint8)
print(num)


[[[215  42 224 219  43]
  [166  69  15 133 255]
  [105  95  54  37 201]
  ...
  [240  22  66 232 132]
  [ 13  85  53 220 170]
  [249  62 221 146  69]]

 [[ 73  79 148 132 164]
  [  3  93  98 138 200]
  [174  34  31 208 130]
  ...
  [ 15 252  41  64  39]
  [188 216 223 124  27]
  [ 85 112 240 116 231]]

 [[227  50 243  20 171]
  [ 12  66 108 102  63]
  [107  54   0   0 173]
  ...
  [215  46  57  99 151]
  [243 199  31  28 179]
  [143   7  30 175 190]]

 ...

 [[214  64  64 212  62]
  [140  44 217  17 164]
  [226 146 247  53 199]
  ...
  [189  68  49 117  63]
  [ 14  17 109  82  92]
  [155 221 135 184 231]]

 [[132 194 160 136 102]
  [132 244 230 117 181]
  [146 245  21 164  29]
  ...
  [125 240 243 190 240]
  [137  41 157 117 155]
  [ 20  92  72 182  41]]

 [[120  45 198 218 190]
  [ 42 150 190 103 106]
  [164  71 220 114  59]
  ...
  [143  20 219 154  85]
  [219 190 170 227 246]
  [ 39  14 127 230 158]]]


## **Sorting & Searching**

In [ ]:
# Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.
shape_2 = np.array([[10,40],[30,20]])
print("original array : ",shape_2 )
sort_fist = np.sort(shape_2,axis = 0)
print("sorted fist axis :",sort_fist)
sort_la = np.sort(shape_2)
print("Sorted last :",sort_la)
sort_flat = np.sort(shape_2,axis=None)
print("Sorted flatten : ",sort_flat)

original array :  [[10 40]
 [30 20]]
sorted fist axis : [[10 20]
 [30 40]]
Sorted last : [[10 40]
 [20 30]]
Sorted flatten :  [10 20 30 40]


In [ ]:
# Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.
data_type = [('sname','S15'),('class','int'),('height','float')]
student_detail = [('sam',10,5.12),('sun',11,4.12),('son',12,4.20)]
student = np.array(student_detail,dtype = data_type)
print("Original array : ",student)
sort_height = np.sort(student,order='height')
print("after sort : ",sort_height)

Original array :  [(b'sam', 10, 5.12) (b'sun', 11, 4.12) (b'son', 12, 4.2 )]
after sort :  [(b'sun', 11, 4.12) (b'son', 12, 4.2 ) (b'sam', 10, 5.12)]


In [ ]:
# Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal.
date_type1 = [('name','S15'),('class','int'),('height','float')]
student_details = [('cat',8,4.12),('dog',7,3.12),('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
students = np.array(student_details,dtype = date_type1)
print("Original array :",students)
sort_height_class = np.sort(students,order=['class','height'])
print("After sorting : ",sort_height_class)


Original array : [(b'cat', 8,  4.12) (b'dog', 7,  3.12) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 ) (b'Pit', 5, 40.11)]
After sorting :  [(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 ) (b'dog', 7,  3.12) (b'cat', 8,  4.12)]


In [ ]:
# Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.

student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])
sort_id = np.lexsort((student_id,student_height)) #to sort index
print("sorted : ",sort_id)
print("After sorted heightwise : ")
for i in sort_id:
  print(student_id[i],student_height[i])


sorted :  [4 0 5 3 6 1 2]
After sorted heightwise : 
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


In [ ]:
# Write a NumPy program to get the indices of the sorted elements of a given array.
ori_array = np.array([1023,5202,6230,1671,1682,5241,4532])
print("original array : ",ori_array)
sort_ori_array = np.argsort((ori_array))
print("indices of sorted array : ",sort_ori_array)

original array :  [1023 5202 6230 1671 1682 5241 4532]
indices of sorted array :  [0 3 4 6 1 5 2]


In [ ]:
# Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.
comx_num = ([1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j])
print("complex num : ",comx_num)
sorted_comx_num = np.sort_complex(comx_num)
print("sorted complex number : ",sorted_comx_num)

complex num :  [(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]
sorted complex number :  [1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]


In [ ]:
# Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order

parti_array = np.array ([70, 50, 20, 30, -11, 60, 50, 40])
print("original array : ",parti_array)
after_part_array =np.partition(parti_array,7)
print("After parition : ",after_part_array)

original array :  [ 70  50  20  30 -11  60  50  40]
After parition :  [-11  30  20  40  50  50  60  70]


In [ ]:
# Write a NumPy program to sort the specified number of elements from beginning of a given array.
sort_specified_no = np.random.random(size=10)
print("original array : ",sort_specified_no)
after_sort_specified_no = np.sort(sort_specified_no)
print("After sort : ",after_sort_specified_no)
after_sort_specified_no1 = np.argpartition(sort_specified_no,range(5))
print("aa",after_sort_specified_no1)

original array :  [0.15021275 0.85617794 0.03077153 0.60427646 0.71523263 0.52098538
 0.8405356  0.03823842 0.81172066 0.73060203]
After sort :  [0.03077153 0.03823842 0.15021275 0.52098538 0.60427646 0.71523263
 0.73060203 0.81172066 0.8405356  0.85617794]
aa [2 7 0 5 3 4 6 1 8 9]


In [ ]:
# Write a NumPy program to sort an given array by the nth column.
sort_matrix = np.random.randint(0,10,(3,3))
print("original matrix : ",sort_matrix)
after_sort_matrix = sort_matrix[sort_matrix[:,2].argsort()]
print("After sorting : ",after_sort_matrix)

original matrix :  [[1 1 8]
 [8 4 9]
 [2 6 6]]
After sorting :  [[2 6 6]
 [1 1 8]
 [8 4 9]]


## **DateTime**

In [ ]:
# Write a NumPy program to display all the dates for the month of March, 2017.
display_date = np.arange('2023-03','2023-04',dtype = 'datetime64[D]')
print("March 2023 : ",display_date)

March 2023 :  ['2023-03-01' '2023-03-02' '2023-03-03' '2023-03-04' '2023-03-05'
 '2023-03-06' '2023-03-07' '2023-03-08' '2023-03-09' '2023-03-10'
 '2023-03-11' '2023-03-12' '2023-03-13' '2023-03-14' '2023-03-15'
 '2023-03-16' '2023-03-17' '2023-03-18' '2023-03-19' '2023-03-20'
 '2023-03-21' '2023-03-22' '2023-03-23' '2023-03-24' '2023-03-25'
 '2023-03-26' '2023-03-27' '2023-03-28' '2023-03-29' '2023-03-30'
 '2023-03-31']


In [ ]:
# Write a NumPy program to get the dates of yesterday, today and tomorrow.
find_yester = np.datetime64('Today','D') - np.timedelta64(1,'D')
print("Yesterday : ",find_yester)
find_today = np.datetime64('Today','D')
print("Today : ",find_today)
find_tomo = np.datetime64('Today','D') + np.timedelta64(1,'D')
print("Tomorrow : ",find_tomo)

Yesterday :  2023-10-18
Today :  2023-10-19
Tomorrow :  2023-10-20


In [ ]:
# Write a NumPy program to count the number of days of specific month.
find_no_days = np.datetime64('2023-06-01') - np.datetime64('2023-05-01')
print("NO of days : ",find_no_days)

NO of days :  31 days
